# Generated by Django 3.2.5 on 2021-07-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
