# Generated by Django 3.2.5 on 2021-07-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0002_cv_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
